version: '3'
services:
  cabeleleila-api:
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - cabeleleila-db

  cabeleleila-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - cabeleleiladb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: numsey

volumes:
    cabeleleiladb:
        
